language: android
android:
  components:
    - andoroid-26

script:
  - ./plugin/gradlew -p ./plugin build --no-daemon
  - ./plugin/gradlew -p ./plugin ktlintCheck --no-daemon
  - ./samples/gradlew -p ./samples :kotlin:ktlintCheck --no-daemon

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
