[versions]
androidXFragment = "1.8.4"
androidXRecyclerView = "1.1.0"
androidMaterial = "1.2.1"
androidXTestRunner = "1.3.0"
androidXEspresso = "3.3.0"
junit = "4.12"

[libraries]
android-material = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidXEspresso" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidXFragment" }
androidx-recycler-view = { module = "androidx.recyclerview:recyclerview", version.ref = "androidXRecyclerView" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidXTestRunner" }
junit = { module = "junit:junit", version.ref = "junit" }
