[versions]
androidXFragment = "1.8.9"
androidXRecyclerView = "1.4.0"
androidMaterial = "1.12.0"
androidXTestRunner = "1.6.2"
androidXEspresso = "3.6.1"
junit = "4.13.2"

[libraries]
android-material = { module = "com.google.android.material:material", version.ref = "androidMaterial" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidXEspresso" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidXFragment" }
androidx-recycler-view = { module = "androidx.recyclerview:recyclerview", version.ref = "androidXRecyclerView" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidXTestRunner" }
junit = { module = "junit:junit", version.ref = "junit" }
